# Generated by Django 6.0.4 on 2026-05-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Marca não informada', max_length=100, verbose_name='Marca')),
                ('model', models.CharField(default='Modelo não informado', max_length=100, verbose_name='Modelo')),
                ('year', models.IntegerField(default=0, verbose_name='Ano')),
                ('plate', models.CharField(default='SEM-PLACA', max_length=20, verbose_name='Placa')),
                ('color', models.CharField(default='Branco', max_length=50, verbose_name='Cor')),
                ('mileage', models.IntegerField(default=0, verbose_name='Quilometragem')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda')),
                ('status', models.CharField(choices=[('estoque', 'Estoque'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='estoque', max_length=20, verbose_name='Status')),
                ('publication_sites', models.CharField(blank=True, default='', max_length=255, verbose_name='Sites de Publicação')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
