# Generated by Django 6.0.4 on 2026-05-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('installments', models.IntegerField(choices=[(1, '1x'), (5, '5x')], default=1, verbose_name='Parcelas')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Final')),
                ('installment_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Parcela')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipvas', to='cars.car', verbose_name='Carro')),
            ],
        ),
    ]
