# Generated by Django 6.0.4 on 2026-05-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='has_cautelar',
            field=models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Tem Cautelar?'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_crlv',
            field=models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Tem CRLV?'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_procuracao',
            field=models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Tem Procuração?'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_spare_key',
            field=models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Tem Chave Reserva?'),
        ),
        migrations.AddField(
            model_name='car',
            name='needs_cleaning',
            field=models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Precisa Limpar?'),
        ),
        migrations.AddField(
            model_name='car',
            name='needs_sanitizing',
            field=models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Precisa Higienizar?'),
        ),
    ]
