# Generated by Django 6.0.4 on 2026-05-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_has_cautelar_car_has_crlv_car_has_procuracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ad_facebook',
            field=models.BooleanField(default=False, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='car',
            name='ad_icarros',
            field=models.BooleanField(default=False, verbose_name='iCarros'),
        ),
        migrations.AddField(
            model_name='car',
            name='ad_instagram',
            field=models.BooleanField(default=False, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='car',
            name='ad_mercado_livre',
            field=models.BooleanField(default=False, verbose_name='Mercado Livre'),
        ),
        migrations.AddField(
            model_name='car',
            name='ad_olx',
            field=models.BooleanField(default=False, verbose_name='OLX'),
        ),
        migrations.AddField(
            model_name='car',
            name='ad_webmotors',
            field=models.BooleanField(default=False, verbose_name='WebMotors'),
        ),
        migrations.AddField(
            model_name='car',
            name='other_ad_sites',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Outros Sites'),
        ),
    ]
