# Generated by Django 6.0.4 on 2026-05-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_ad_facebook_car_ad_icarros_car_ad_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fipe_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código FIPE'),
        ),
        migrations.AddField(
            model_name='car',
            name='fipe_current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Atual FIPE'),
        ),
        migrations.AddField(
            model_name='car',
            name='fipe_initial_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Inicial FIPE'),
        ),
    ]
