# Generated by Django 6.0.4 on 2026-05-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_fipe_code_car_fipe_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
    ]
