# Generated by Django 6.0.4 on 2026-05-01 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_observations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Venda')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lucro')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do Comprador')),
                ('sale_date', models.DateField(auto_now_add=True, verbose_name='Data da Venda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='cars.car', verbose_name='Carro')),
            ],
        ),
    ]
