# Generated by Django 6.0.4 on 2026-05-01 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_type',
            field=models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], default='fisica', max_length=20, verbose_name='Tipo de Comprador'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='sale',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='sale',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='sale',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Venda'),
        ),
    ]
