# Generated by Django 6.0.4 on 2026-05-01 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_sale_address_sale_buyer_type_sale_cpf_sale_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('crlv', 'CRLV'), ('nota_fiscal', 'Nota Fiscal'), ('recibo', 'Recibo'), ('contrato', 'Contrato'), ('laudo', 'Laudo'), ('seguro', 'Seguro'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Documento')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Documento')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cars.car', verbose_name='Carro')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/', verbose_name='Imagem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.vehicledocument')),
            ],
        ),
    ]
