# Generated by Django 6.0.4 on 2026-05-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_vehicledocument_vehicledocumentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_password_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='Senha de Proteção')),
                ('itau_email_encrypted', models.TextField(blank=True, default='', verbose_name='E-mail Itaú Criptografado')),
                ('itau_password_encrypted', models.TextField(blank=True, default='', verbose_name='Senha Itaú Criptografada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
